from .aspect_ratio_node import NODE_CLASS_MAPPINGS as AR_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AR_NODE_DISPLAY_NAME_MAPPINGS
from .seed_generator import NODE_CLASS_MAPPINGS as SG_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SG_NODE_DISPLAY_NAME_MAPPINGS

# Merge node mappings
NODE_CLASS_MAPPINGS = {**AR_NODE_CLASS_MAPPINGS, **SG_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**AR_NODE_DISPLAY_NAME_MAPPINGS, **SG_NODE_DISPLAY_NAME_MAPPINGS}

WEB_DIRECTORY = "web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]